version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - SECRET_KEY_BASE=secret mongodb://localhost:27017/SalaryChange
      - MONGO_URL=mongodb://$MONGO_HOSTNAME:$MONGO_PORT/$MONGO_DB
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db

  
  mongo_db:
    image: mongo
    env_file: .env
    ports:
      - 27017:27017
    restart: unless-stopped